---
title: Dead Wood Space
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title"
email: hello@ldaniel.eu
description: 'Saves no lives today.

'
baseurl: 
url: http://deadwood.space
twitter_username: ldanielswakman
github_username: ldanielswakman
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
